export const data: { [key: string]: any } = {
    "Employees":
        [
            {
                "FirstName": "Kate",
                "LastName": "Lorenz",
                "HireDate": "Jul. 1, 2022",
                "Siblings": ["Sofie, Billy, Dyna"],
                "ID": 16,
                "Department": "Development",
                "Position": "Product Manager",
                "Email": "klorenz@hrcorp.com",
                "Phone": "0123-456-789",
                "Photo": "https://d3cg6cexo8t5ug.cloudfront.net/avatars/avatar2.png"
            },
            {
                "FirstName": "Anthony",
                "LastName": "Murray",
                "HireDate": "Jul. 1, 2022",
                "Siblings": ["Sofie, Billy, Dyna"],
                "ID": 15,
                "Department": "Sales",
                "Position": "Sales Associate",
                "Email": "amurray@hrcorp.com",
                "Phone": "0246-333-2108",
                "Photo": "https://d3cg6cexo8t5ug.cloudfront.net/avatars/avatar8.png"
            },
            {
                "FirstName": "Tatiana",
                "LastName": "Rivers",
                "HireDate": "Jun. 1, 2022",
                "Siblings": ["Sofie, Billy, Dyna"],
                "ID": 14,
                "Department": "Design",
                "Position": "Visual Designer",
                "Email": "trivers@hrcorp.com",
                "Phone": "0789-123-456",
                "Photo": "https://d3cg6cexo8t5ug.cloudfront.net/avatars/avatar6.png"
            },
            {
                "FirstName": "Thomas",
                "LastName": "Scott",
                "HireDate": "Jun. 1, 2022",
                "Siblings": ["Sofie, Billy, Dyna"],
                "ID": 13,
                "Department": "Development",
                "Position": "Developer",
                "Email": "tscott@hrcorp.com",
                "Phone": "0966-341-257",
                "Photo": "https://d3cg6cexo8t5ug.cloudfront.net/avatars/avatar5.png"
            },
            {
                "FirstName": "Leif",
                "LastName": "Newis",
                "HireDate": "May. 3, 2022",
                "Siblings": ["Sofie, Billy, Dyna"],
                "ID": 12,
                "Department": "Design",
                "Position": "UX Designer",
                "Email": "lnewis@hrcorp.com",
                "Phone": "0456-789-123",
                "Photo": "https://d3cg6cexo8t5ug.cloudfront.net/avatars/avatar1.png"
            },
            {
                "FirstName": "Lisa",
                "LastName": "Carlton",
                "HireDate": "May. 3, 2022",
                "Siblings": ["Sofie, Billy, Dyna"],
                "ID": 11,
                "Department": "Sales",
                "Position": "Sales Associate",
                "Email": "lcarlton@hrcorp.com",
                "Phone": "0255-123-095",
                "Photo": "https://d3cg6cexo8t5ug.cloudfront.net/avatars/avatar7.png"
            },
            {
                "FirstName": "Ruddy",
                "LastName": "Bettam",
                "HireDate": "Apr. 4, 2022",
                "Siblings": ["Sofie, Billy, Dyna"],
                "ID": 10,
                "Department": "Development",
                "Position": "Developer",
                "Email": "rbettam@hrcorp.com",
                "Phone": "0813-666-025",
                "Photo": "https://d3cg6cexo8t5ug.cloudfront.net/avatars/avatar3.png"
            },
            {
                "FirstName": "Haley",
                "LastName": "Barukh",
                "HireDate": "Apr. 4, 2022",
                "Siblings": ["Sofie, Billy, Dyna"],
                "ID": 9,
                "Department": "Development",
                "Position": "Developer",
                "Email": "hbarukh@hrcorp.com",
                "Phone": "0966-123-987",
                "Photo": "https://d3cg6cexo8t5ug.cloudfront.net/avatars/avatar10.png"
            },
            {
                "FirstName": "Jade",
                "LastName": "Maruska",
                "HireDate": "Mar. 1, 2022",
                "Siblings": ["Sofie, Billy, Dyna"],
                "ID": 8,
                "Department": "Development",
                "Position": "Product Manager",
                "Email": "jmaruska@hrcorp.com",
                "Phone": "0123-456-789",
                "Photo": "https://d3cg6cexo8t5ug.cloudfront.net/avatars/avatar12.png"
            },
            {
                "FirstName": "Willy",
                "LastName": "MacKettrick",
                "HireDate": "Mar. 1, 2022",
                "Siblings": ["Sofie, Billy, Dyna"],
                "ID": 7,
                "Department": "Sales",
                "Position": "Sales Associate",
                "Email": "wmackettrick@hrcorp.com",
                "Phone": "0246-333-2108",
                "Photo": "https://d3cg6cexo8t5ug.cloudfront.net/avatars/avatar9.png"
            },
            {
                "FirstName": "Susy",
                "LastName": "Berenson",
                "HireDate": "Mar. 1, 2022",
                "Siblings": ["Sofie, Billy, Dyna"],
                "ID": 6,
                "Department": "Marketing",
                "Position": "Developer",
                "Email": "sberenson@hrcorp.com",
                "Phone": "0789-123-456",
                "Photo": "https://d3cg6cexo8t5ug.cloudfront.net/avatars/avatar14.png"
            },
            {
                "FirstName": "Sybill",
                "LastName": "Newman",
                "HireDate": "Feb. 3, 2022",
                "Siblings": ["Sofie, Billy, Dyna"],
                "ID": 5,
                "Department": "Marketing",
                "Position": "Visual Designer",
                "Email": "snewman@hrcorp.com",
                "Phone": "0966-341-257",
                "Photo": "https://d3cg6cexo8t5ug.cloudfront.net/avatars/avatar13.png"
            },
            {
                "FirstName": "Brian",
                "LastName": "Robertson",
                "HireDate": "Feb. 3, 2022",
                "Siblings": ["Sofie, Billy, Dyna"],
                "ID": 4,
                "Department": "Sales",
                "Position": "Sales Manager",
                "Email": "brobertson@hrcorp.com",
                "Phone": "0456-789-123",
                "Photo": "https://d3cg6cexo8t5ug.cloudfront.net/avatars/avatar11.png"
            },
            {
                "FirstName": "Brigitte",
                "LastName": "Kowalsky",
                "HireDate": "Jan. 4, 2022",
                "Siblings": ["Sofie, Billy, Dyna"],
                "ID": 3,
                "Department": "Design",
                "Position": "UX Designer",
                "Email": "bkowalsky@hrcorp.com",
                "Phone": "0255-123-095",
                "Photo": "https://d3cg6cexo8t5ug.cloudfront.net/avatars/avatar2.png"
            },
            {
                "FirstName": "Rolland",
                "LastName": "Truman",
                "HireDate": "Jan. 4, 2022",
                "Siblings": ["Sofie, Billy, Dyna"],
                "ID": 2,
                "Department": "Development",
                "Position": "Developer",
                "Email": "rtruman@hrcorp.com",
                "Phone": "0134-233-987",
                "Photo": "https://d3cg6cexo8t5ug.cloudfront.net/avatars/avatar4.png"
            },
            {
                "FirstName": "Sandy",
                "LastName": "Anderson",
                "HireDate": "Jan. 4, 2022",
                "Siblings": ["Sofie, Billy, Dyna"],
                "ID": 1,
                "Department": "Design",
                "Position": "UX Design Lead",
                "Email": "sanderson@hrcorp.com",
                "Phone": "0813-666-025",
                "Photo": "https://d3cg6cexo8t5ug.cloudfront.net/avatars/avatar13.png"
            }
        ],
    "Siblings": [
        "Sofie",
        "Johannes",
        "Billy",
        "Dilan",
        "Barclay",
        "Eyde",
        "Brandi",
        "Cathe",
        "Lowell",
        "Wallie",
        "Edlin",
        "Brenna",
        "Esmaria",
        "Isis",
        "Dyna",
        "Andonis",
        "Aurea",
        "Friederike",
        "Arri",
        "Gaultiero"
    ]
}